---
- hosts: testidracs
  connection: local
  name: Get idrac facts
  gather_facts: false

  tasks:

    - name: Get BIOS attributes
      community.general.redfish_info:
        category: Systems
        command: GetBiosAttributes
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result
      when: true

    - name: Print output
      ansible.builtin.debug:
        msg: "{{ result }}"
      when: true

    - name: upload uefi.json file
      dellemc.openmanage.idrac_server_config_profile:
        idrac_ip: "{{ baseuri }}"
        idrac_user: "{{ username }}"
        idrac_password: "{{ password }}"
        share_name: files
        scp_file: R7425-uefi.json
        command: import
        job_wait: true
      register: some_values
      when: false

    - name: Output some vars
      ansible.builtin.debug:
        msg: "{{ some_values }}"
      when: false
